In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
df2 = pd.read_csv("test.csv", parse_dates=['joining_date'])
print(df2.info())
print(df2.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19919 entries, 0 to 19918
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype         
---  ------                        --------------  -----         
 0   customer_id                   19919 non-null  object        
 1   Name                          19919 non-null  object        
 2   age                           19919 non-null  int64         
 3   gender                        19919 non-null  object        
 4   security_no                   19919 non-null  object        
 5   region_category               16971 non-null  object        
 6   membership_category           19919 non-null  object        
 7   joining_date                  19919 non-null  datetime64[ns]
 8   joined_through_referral       19919 non-null  object        
 9   referral_id                   19919 non-null  object        
 10  preferred_offer_types         19760 non-null  object        
 11  medium_of_operation         

In [3]:
df1 = pd.read_csv("train.csv", parse_dates=['joining_date'])
#parse_dates=['joining_date']
y = df1["churn_risk_score"]
#df1=df1.drop("churn_risk_score", axis=1)
df1.churn_risk_score.dtypes

dtype('int64')

In [4]:
print(len(df1.columns))
print(len(df2.columns))
print((df1.shape))
print((df2.shape))

25
24
(36992, 25)
(19919, 24)


In [5]:
df1.set_index("customer_id", inplace=True)

In [6]:
df2.set_index("customer_id", inplace=True)

In [7]:
df1.head()

Name  age gender  \
customer_id                                                          
fffe4300490044003600300030003800       Pattie Morrisey   18      F   
fffe43004900440032003100300035003700       Traci Peery   32      F   
fffe4300490044003100390032003600       Merideth Mcmeen   44      F   
fffe43004900440036003000330031003600  Eufemia Cardwell   37      M   
fffe43004900440031003900350030003600      Meghan Kosak   31      F   

                                     security_no region_category  \
customer_id                                                        
fffe4300490044003600300030003800         XW0DQ7H         Village   
fffe43004900440032003100300035003700     5K0N3X1            City   
fffe4300490044003100390032003600         1F2TCL3            Town   
fffe43004900440036003000330031003600     VJGJ33N            City   
fffe43004900440031003900350030003600     SVZXCWB            City   

                                      membership_category joining_date  \
customer_id                                                              
fffe4300490044003600300030003800      Platinum Membership   2017-08-17   
fffe43004900440032003100300035003700   Premium Membership   2017-08-28   
fffe4300490044003100390032003600            No Membership   2016-11-11   
fffe43004900440036003000330031003600        No Membership   2016-10-29   
fffe43004900440031003900350030003600        No Membership   2017-09-12   

                                     joined_through_referral referral_id  \
customer_id                                                                
fffe4300490044003600300030003800                          No    xxxxxxxx   
fffe43004900440032003100300035003700                       ?    CID21329   
fffe4300490044003100390032003600                         Yes    CID12313   
fffe43004900440036003000330031003600                     Yes     CID3793   
fffe43004900440031003900350030003600                      No    xxxxxxxx   

                                         preferred_offer_types  ...  \
customer_id                                                     ...   
fffe4300490044003600300030003800         Gift Vouchers/Coupons  ...   
fffe43004900440032003100300035003700     Gift Vouchers/Coupons  ...   
fffe4300490044003100390032003600         Gift Vouchers/Coupons  ...   
fffe43004900440036003000330031003600     Gift Vouchers/Coupons  ...   
fffe43004900440031003900350030003600  Credit/Debit Card Offers  ...   

                                     avg_time_spent avg_transaction_value  \
customer_id                                                                 
fffe4300490044003600300030003800             300.63              53005.25   
fffe43004900440032003100300035003700         306.34              12838.38   
fffe4300490044003100390032003600             516.16              21027.00   
fffe43004900440036003000330031003600          53.27              25239.56   
fffe43004900440031003900350030003600         113.13              24483.66   

                                     avg_frequency_login_days  \
customer_id                                                     
fffe4300490044003600300030003800                         17.0   
fffe43004900440032003100300035003700                     10.0   
fffe4300490044003100390032003600                         22.0   
fffe43004900440036003000330031003600                      6.0   
fffe43004900440031003900350030003600                     16.0   

                                      points_in_wallet  used_special_discount  \
customer_id                                                                     
fffe4300490044003600300030003800                781.75                    Yes   
fffe43004900440032003100300035003700               NaN                    Yes   
fffe4300490044003100390032003600                500.69                     No   
fffe43004900440036003000330031003600            567.66                     No   
fffe43004900440031003900350030003600            66

In [8]:
print(df1.shape)  
print(df2.shape)

(36992, 24)
(19919, 23)


In [9]:
print("Total columns =",len(df1.columns))
print(df1.columns)

Total columns = 24
Index(['Name', 'age', 'gender', 'security_no', 'region_category',
       'membership_category', 'joining_date', 'joined_through_referral',
       'referral_id', 'preferred_offer_types', 'medium_of_operation',
       'internet_option', 'last_visit_time', 'days_since_last_login',
       'avg_time_spent', 'avg_transaction_value', 'avg_frequency_login_days',
       'points_in_wallet', 'used_special_discount',
       'offer_application_preference', 'past_complaint', 'complaint_status',
       'feedback', 'churn_risk_score'],
      dtype='object')


In [10]:
df1 = df1.drop(["Name","security_no","referral_id","last_visit_time"], axis=1)
df1.head(2)

age gender region_category  \
customer_id                                                        
fffe4300490044003600300030003800       18      F         Village   
fffe43004900440032003100300035003700   32      F            City   

                                      membership_category joining_date  \
customer_id                                                              
fffe4300490044003600300030003800      Platinum Membership   2017-08-17   
fffe43004900440032003100300035003700   Premium Membership   2017-08-28   

                                     joined_through_referral  \
customer_id                                                    
fffe4300490044003600300030003800                          No   
fffe43004900440032003100300035003700                       ?   

                                      preferred_offer_types  \
customer_id                                                   
fffe4300490044003600300030003800      Gift Vouchers/Coupons   
fffe43004900440032003100300035003700  Gift Vouchers/Coupons   

                                     medium_of_operation internet_option  \
customer_id                                                                
fffe4300490044003600300030003800                       ?           Wi-Fi   
fffe43004900440032003100300035003700             Desktop     Mobile_Data   

                                      days_since_last_login  avg_time_spent  \
customer_id                                                                   
fffe4300490044003600300030003800                         17          300.63   
fffe43004900440032003100300035003700                     16          306.34   

                                      avg_transaction_value  \
customer_id                                                   
fffe4300490044003600300030003800                   53005.25   
fffe43004900440032003100300035003700               12838.38   

                                     avg_frequency_login_days  \
customer_id                                                     
fffe4300490044003600300030003800                         17.0   
fffe43004900440032003100300035003700                     10.0   

                                      points_in_wallet used_special_discount  \
customer_id                                                                    
fffe4300490044003600300030003800                781.75                   Yes   
fffe43004900440032003100300035003700               NaN                   Yes   

                                     offer_application_preference  \
customer_id                                                         
fffe4300490044003600300030003800                              Yes   
fffe43004900440032003100300035003700                           No   

                                     past_complaint complaint_status  \
customer_id                                                            
fffe4300490044003600300030003800                 No   Not Applicable   
fffe43004900440032003100300035003700            Yes           Solved   

                                                      feedback  \
customer_id                                                      
fffe4300490044003600300030003800      Products always in Stock   
fffe43004900440032003100300035003700     Quality Customer Care   

                                      churn_risk_score  
customer_id                                             
fffe4300490044003600300030003800                     2  
fffe43004900440032003100300035003700                 1

In [11]:
df2 = df2.drop(["Name","security_no","referral_id","last_visit_time"], axis=1)
df2.head(2)

age gender region_category  \
customer_id                                                        
fffe43004900440031003700300030003400   50      F         Village   
fffe43004900440031003900370037003300   41      M         Village   

                                     membership_category joining_date  \
customer_id                                                             
fffe43004900440031003700300030003400  Premium Membership   2015-11-02   
fffe43004900440031003900370037003300     Gold Membership   2016-03-01   

                                     joined_through_referral  \
customer_id                                                    
fffe43004900440031003700300030003400                      No   
fffe43004900440031003900370037003300                      No   

                                     preferred_offer_types  \
customer_id                                                  
fffe43004900440031003700300030003400        Without Offers   
fffe43004900440031003900370037003300        Without Offers   

                                     medium_of_operation internet_option  \
customer_id                                                                
fffe43004900440031003700300030003400          Smartphone           Wi-Fi   
fffe43004900440031003900370037003300             Desktop     Fiber_Optic   

                                      days_since_last_login  avg_time_spent  \
customer_id                                                                   
fffe43004900440031003700300030003400                     12          386.26   
fffe43004900440031003900370037003300                     11           37.80   

                                      avg_transaction_value  \
customer_id                                                   
fffe43004900440031003700300030003400               40721.44   
fffe43004900440031003900370037003300                9644.40   

                                     avg_frequency_login_days  \
customer_id                                                     
fffe43004900440031003700300030003400                      7.0   
fffe43004900440031003900370037003300                      9.0   

                                      points_in_wallet used_special_discount  \
customer_id                                                                    
fffe43004900440031003700300030003400            733.83                   Yes   
fffe43004900440031003900370037003300            726.00                   Yes   

                                     offer_application_preference  \
customer_id                                                         
fffe43004900440031003700300030003400                           No   
fffe43004900440031003900370037003300                           No   

                                     past_complaint complaint_status  \
customer_id                                                            
fffe43004900440031003700300030003400             No   Not Applicable   
fffe43004900440031003900370037003300             No   Not Applicable   

                                                  feedback  
customer_id                                                 
fffe43004900440031003700300030003400  Poor Product Quality  
fffe43004900440031003900370037003300          Poor Website

In [12]:
df1.dtypes

age                                      int64
gender                                  object
region_category                         object
membership_category                     object
joining_date                    datetime64[ns]
joined_through_referral                 object
preferred_offer_types                   object
medium_of_operation                     object
internet_option                         object
days_since_last_login                    int64
avg_time_spent                         float64
avg_transaction_value                  float64
avg_frequency_login_days                object
points_in_wallet                       float64
used_special_discount                   object
offer_application_preference            object
past_complaint                          object
complaint_status                        object
feedback                                object
churn_risk_score                         int64
dtype: object

In [13]:
for i in df1.columns:
    if df1[i].dtype == 'O':
        print(i,":",len(df1[i].unique()))

gender : 3
region_category : 4
membership_category : 6
joined_through_referral : 3
preferred_offer_types : 4
medium_of_operation : 4
internet_option : 3
avg_frequency_login_days : 1654
used_special_discount : 2
offer_application_preference : 2
past_complaint : 2
complaint_status : 5
feedback : 9


In [14]:
df1["avg_frequency_login_days"].value_counts()                 #-22.27092071489964 which type of values r these

Error                 3522
13.0                  1394
19.0                  1365
8.0                   1361
14.0                  1355
                      ... 
38.171638711704205       1
-2.6593049208238         1
33.506499367317765       1
49.2967272346713         1
31.627609933736142       1
Name: avg_frequency_login_days, Length: 1654, dtype: int64

In [15]:
df1.replace('Error', np.NaN, inplace=True)

In [16]:
df2.replace('Error', np.NaN, inplace=True)

In [17]:
df1["avg_frequency_login_days"] = df1["avg_frequency_login_days"].astype("O").astype("float64")

In [18]:
df2["avg_frequency_login_days"] = df2["avg_frequency_login_days"].astype("O").astype("float64")

In [19]:
for category in ["gender","region_category","membership_category","joined_through_referral",
                 "preferred_offer_types","medium_of_operation","internet_option","used_special_discount",
                 "offer_application_preference","past_complaint","complaint_status","feedback","churn_risk_score"]:
    print(category + "------------------------------------------------------")
    print(df1[category].value_counts())

gender------------------------------------------------------
F          18490
M          18443
Unknown       59
Name: gender, dtype: int64
region_category------------------------------------------------------
Town       14128
City       12737
Village     4699
Name: region_category, dtype: int64
membership_category------------------------------------------------------
Basic Membership       7724
No Membership          7692
Gold Membership        6795
Silver Membership      5988
Premium Membership     4455
Platinum Membership    4338
Name: membership_category, dtype: int64
joined_through_referral------------------------------------------------------
No     15839
Yes    15715
?       5438
Name: joined_through_referral, dtype: int64
preferred_offer_types------------------------------------------------------
Gift Vouchers/Coupons       12349
Credit/Debit Card Offers    12274
Without Offers              12081
Name: preferred_offer_types, dtype: int64
medium_of_operation----------------------

In [20]:
# # drop 59/36992  rows as in gender its unknown
# index_names = df1[ df1['gender'] == 'Unknown' ].index
# df1.drop(index_names, inplace = True)
# #df1=df1.drop(index_names, inplace = True)

# # drop 296/36992  rows as in churn_risk_score its -1
# index_names1 = df1[ df1['churn_risk_score'] == -1 ].index
# df1.drop(index_names1, inplace = True)

In [21]:
# index_names2 = df2[ df2['gender'] == 'Unknown' ].index
# df1.drop(index_names, inplace = True)

In [22]:
df1.replace('?', np.NaN, inplace = True)         #unknown -left

In [23]:
df2.replace('?', np.NaN, inplace = True)

In [24]:
#features, no of null values & data types
for i in df1.columns:
    if df1[i].isnull().sum()>0:
        print(i,"---->", df1[i].isnull().sum(), "null values &", df1[i].dtypes )

region_category ----> 5428 null values & object
joined_through_referral ----> 5438 null values & object
preferred_offer_types ----> 288 null values & object
medium_of_operation ----> 5393 null values & object
avg_frequency_login_days ----> 3522 null values & float64
points_in_wallet ----> 3443 null values & float64


In [25]:
#random sample
def impute_nan(df,variable):
    #df[variable+"_median"]=df[variable].fillna(median)
    df[variable+"_random"]=df[variable]
    random_sample=df[variable].dropna().sample(df[variable].isnull().sum(), random_state=0)
    random_sample.index=df[df[variable].isnull()].index
    df.loc[df[variable].isnull(),variable+"_random"]=random_sample

In [26]:
#all has been replaced with random sample
for feature in ["region_category", "joined_through_referral", "preferred_offer_types", 
                "medium_of_operation", "avg_frequency_login_days","points_in_wallet"]:
    impute_nan(df1, feature)
    impute_nan(df2, feature)

In [27]:
# # variance distortion checking for only dtype - float features,  randomly imputed
# fig=plt.figure()
# ax=fig.add_subplot(111)
# df1['avg_frequency_login_days'].plot(kind='kde', ax=ax, color='blue')
# #df1['points_in_wallet_median'].plot(kind='kde', ax=ax, color='blue')
# df1['avg_frequency_login_days_random'].plot(kind='kde', ax=ax, color='red')
# lines, labels=ax.get_legend_handles_labels()
# ax.legend(lines,labels,loc='best')

In [28]:
df1 = df1.drop(["region_category", "joined_through_referral", "preferred_offer_types",
          "medium_of_operation", "avg_frequency_login_days", "points_in_wallet"], axis=1)

In [29]:
df2 = df2.drop(["region_category", "joined_through_referral", "preferred_offer_types",
          "medium_of_operation", "avg_frequency_login_days", "points_in_wallet"], axis=1)

In [30]:
df1.isnull().sum()

age                                0
gender                             0
membership_category                0
joining_date                       0
internet_option                    0
days_since_last_login              0
avg_time_spent                     0
avg_transaction_value              0
used_special_discount              0
offer_application_preference       0
past_complaint                     0
complaint_status                   0
feedback                           0
churn_risk_score                   0
region_category_random             0
joined_through_referral_random     0
preferred_offer_types_random       0
medium_of_operation_random         0
avg_frequency_login_days_random    0
points_in_wallet_random            0
dtype: int64

In [31]:
df1['days']=(pd.to_datetime("2021-03-16")-df1['joining_date'])/np.timedelta64(1,'D')

df1.drop("joining_date",axis=1, inplace = True)

In [32]:
df2['days']=(pd.to_datetime("2021-03-16")-df2['joining_date'])/np.timedelta64(1,'D')

df2.drop("joining_date",axis=1, inplace = True)

In [33]:
df1['membership_category'].value_counts()

Basic Membership       7724
No Membership          7692
Gold Membership        6795
Silver Membership      5988
Premium Membership     4455
Platinum Membership    4338
Name: membership_category, dtype: int64

In [34]:
replace_map = {'membership_category': {'No Membership': 1, 'Basic Membership': 2, 'Premium Membership': 3, 'Silver Membership': 4,
                                         'Gold Membership': 5, 'Platinum Membership': 6}}
df1.replace(replace_map, inplace=True)
df2.replace(replace_map, inplace=True)
#df1['membership_category'].dtypes

In [35]:
replace_map1 = {'feedback': {'Poor Product Quality': 1, 'Too many ads': 2, 'No reason specified':3, 
                             'Poor Customer Service': 4,'Poor Website':5, 'Reasonable Price': 6, 'User Friendly Website':7,
                             'Products always in Stock':8, 'Quality Customer Care':9}}
df1.replace(replace_map1, inplace=True)
df2.replace(replace_map1, inplace=True)
#df1['feedback'].dtypes

In [36]:
df1['feedback'].value_counts()

1    6350
3    6290
2    6279
5    6271
4    6252
6    1417
7    1391
8    1382
9    1360
Name: feedback, dtype: int64

In [37]:
df1['internet_option'].value_counts()

Wi-Fi          12413
Mobile_Data    12343
Fiber_Optic    12236
Name: internet_option, dtype: int64

In [38]:
df1 = pd.get_dummies(df1, drop_first=False)
df2 = pd.get_dummies(df2, drop_first=False)

In [39]:
df1.head()

age  membership_category  \
customer_id                                                      
fffe4300490044003600300030003800       18                    6   
fffe43004900440032003100300035003700   32                    3   
fffe4300490044003100390032003600       44                    1   
fffe43004900440036003000330031003600   37                    1   
fffe43004900440031003900350030003600   31                    1   

                                      days_since_last_login  avg_time_spent  \
customer_id                                                                   
fffe4300490044003600300030003800                         17          300.63   
fffe43004900440032003100300035003700                     16          306.34   
fffe4300490044003100390032003600                         14          516.16   
fffe43004900440036003000330031003600                     11           53.27   
fffe43004900440031003900350030003600                     20          113.13   

                                      avg_transaction_value  feedback  \
customer_id                                                             
fffe4300490044003600300030003800                   53005.25         8   
fffe43004900440032003100300035003700               12838.38         9   
fffe4300490044003100390032003600                   21027.00         5   
fffe43004900440036003000330031003600               25239.56         5   
fffe43004900440031003900350030003600               24483.66         5   

                                      churn_risk_score  \
customer_id                                              
fffe4300490044003600300030003800                     2   
fffe43004900440032003100300035003700                 1   
fffe4300490044003100390032003600                     5   
fffe43004900440036003000330031003600                 5   
fffe43004900440031003900350030003600                 5   

                                      avg_frequency_login_days_random  \
customer_id                                                             
fffe4300490044003600300030003800                                 17.0   
fffe43004900440032003100300035003700                             10.0   
fffe4300490044003100390032003600                                 22.0   
fffe43004900440036003000330031003600                              6.0   
fffe43004900440031003900350030003600                             16.0   

                                      points_in_wallet_random    days  ...  \
customer_id                                                            ...   
fffe4300490044003600300030003800                       781.75  1307.0  ...   
fffe43004900440032003100300035003700                   715.36  1296.0  ...   
fffe4300490044003100390032003600                       500.69  1586.0  ...   
fffe43004900440036003000330031003600                   567.66  1599.0  ...   
fffe43004900440031003900350030003600                   663.06  1281.0  ...   

                                      region_category_random_Town  \
customer_id                                                         
fffe4300490044003600300030003800                                0   
fffe43004900440032003100300035003700                            0   
fffe4300490044003100390032003600                                1   
fffe43004900440036003000330031003600                            0   
fffe43004900440031003900350030003600                            0   

                                      region_category_random_Village  \
customer_id                                                            
fffe4300490044003600300030003800                                   1   
fffe43004900440032003100300035003700                               0   
fffe4300490044003100390032003600                                   0   
fffe43004900440036003000330031003600                               0   
fffe43004900440031003900350030003600                               0   

                                      joined_through_r

In [40]:
df1.dtypes

age                                                        int64
membership_category                                        int64
days_since_last_login                                      int64
avg_time_spent                                           float64
avg_transaction_value                                    float64
feedback                                                   int64
churn_risk_score                                           int64
avg_frequency_login_days_random                          float64
points_in_wallet_random                                  float64
days                                                     float64
gender_F                                                   uint8
gender_M                                                   uint8
gender_Unknown                                             uint8
internet_option_Fiber_Optic                                uint8
internet_option_Mobile_Data                                uint8
internet_option_Wi-Fi    

In [41]:
len(df1.columns)

38

In [42]:
X = df1.drop("churn_risk_score", axis=1)
print(len(X.columns))
y=df1["churn_risk_score"]
y.head()

37


customer_id
fffe4300490044003600300030003800        2
fffe43004900440032003100300035003700    1
fffe4300490044003100390032003600        5
fffe43004900440036003000330031003600    5
fffe43004900440031003900350030003600    5
Name: churn_risk_score, dtype: int64

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [44]:
#feature scaling is required when algorithm is based on euclidean distance, DT not required but for visualization required.
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
df2=sc.transform(df2)

In [45]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy', random_state=0)
classifier.fit(X_train, y_train)
y_pred= classifier.predict(X_test)
df2_pred = classifier.predict(df2)

In [46]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print(f"Test Set Accuracy : {accuracy_score(y_test, y_pred) * 100} %\n\n")
print(f"Classification Report : \n\n{classification_report(y_test, y_pred)}")
print("\n", confusion_matrix(y_test, y_pred))

Test Set Accuracy : 70.24221453287197 %


Classification Report : 

              precision    recall  f1-score   support

          -1       0.04      0.05      0.04       280
           1       0.72      0.69      0.71       674
           2       0.71      0.73      0.72       669
           3       0.86      0.86      0.86      2596
           4       0.61      0.60      0.61      2567
           5       0.72      0.71      0.71      2462

    accuracy                           0.70      9248
   macro avg       0.61      0.61      0.61      9248
weighted avg       0.71      0.70      0.71      9248


 [[  14   19    8   81   92   66]
 [  20  467  187    0    0    0]
 [  21  161  487    0    0    0]
 [ 105    0    0 2231  260    0]
 [ 120    0    0  278 1542  627]
 [  90    0    0    0  617 1755]]


In [47]:
y_test.value_counts()

 3    2596
 4    2567
 5    2462
 1     674
 2     669
-1     280
Name: churn_risk_score, dtype: int64

In [48]:
# from sklearn.ensemble import RandomForestClassifier
# classifier_rf = RandomForestClassifier(n_estimators = 300, criterion = 'entropy', random_state = 42)
# classifier_rf.fit(X_train, y_train)
# rf_predictions = classifier_rf.predict(X_test)
# print(classifier_rf.score(X_test, y_test))
# print(confusion_matrix(y_test, rf_predictions))
#print(f"Classification Report : \n\n{classification_report(y_test, rf_predictions)}")
#print(f"Classification Report : \n\n{classifier_rf.feature_importances_}")

In [49]:
n_estimators = [25]
max_depth = [25]
min_samples_leaf = [2]
bootstrap = [True, False]

param_grid = {
    "n_estimators": n_estimators,
    "max_depth": max_depth,
    "min_samples_leaf": min_samples_leaf,
    "bootstrap": bootstrap,
}

from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(random_state=42)

from sklearn.model_selection import GridSearchCV
rf_model = GridSearchCV(estimator=rf, param_grid=param_grid, cv=2, verbose=10, n_jobs=-1)
rf_model.fit(X_train, y_train)

print("Using hyperparameters --> \n", rf_model.best_params_)

Fitting 2 folds for each of 2 candidates, totalling 4 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done   1 tasks      | elapsed:    8.5s
[Parallel(n_jobs=-1)]: Done   2 out of   4 | elapsed:    8.5s remaining:    8.5s
[Parallel(n_jobs=-1)]: Done   4 out of   4 | elapsed:   11.1s remaining:    0.0s
[Parallel(n_jobs=-1)]: Done   4 out of   4 | elapsed:   11.1s finished


Using hyperparameters --> 
 {'bootstrap': True, 'max_depth': 25, 'min_samples_leaf': 2, 'n_estimators': 25}


In [50]:
y_pred = rf_model.predict(X_test)
y_pred

array([2.92091966, 1.735     , 3.25866667, ..., 4.80533333, 3.19555556,
       2.46666667])

In [51]:
y_pred=np.rint(y_pred)

In [52]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print(f"Test Set Accuracy : {accuracy_score(y_test, y_pred) * 100} %\n\n")
print(f"Classification Report : \n\n{classification_report(y_test, y_pred)}")
print("\n", confusion_matrix(y_test, y_pred))

Test Set Accuracy : 68.6310553633218 %


Classification Report : 

              precision    recall  f1-score   support

        -1.0       0.00      0.00      0.00       280
         0.0       0.00      0.00      0.00         0
         1.0       0.68      0.83      0.75       674
         2.0       0.57      0.63      0.60       669
         3.0       0.80      0.87      0.83      2596
         4.0       0.57      0.69      0.62      2567
         5.0       0.78      0.54      0.63      2462

    accuracy                           0.69      9248
   macro avg       0.48      0.51      0.49      9248
weighted avg       0.68      0.69      0.67      9248


 [[   0    0   20   15   97  101   47]
 [   0    0    0    0    0    0    0]
 [   0   11  562  101    0    0    0]
 [   0    0  247  422    0    0    0]
 [   0    0    1  184 2267  144    0]
 [   0    0    1   20  439 1775  332]
 [   0    0    0    2   45 1094 1321]]


C:\Users\sarokuma\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\sarokuma\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [53]:
# just concat the customer id column  & y_pred

In [ ]:
#df["avg_frequency_login_days"] = df["avg_frequency_login_days"].astype("O").astype("float64")